# Service for reading MKS Servo 42D/57D motor data
# Request
uint32 motor_id
string read_type  # "encoder", "speed", "io_status", "motor_status"

---
# Response
bool success
string message

# Encoder data
int64 encoder_raw_value
float64 encoder_angle_degrees
float64 encoder_angle_radians

# Speed data
int16 speed_rpm
float64 speed_rad_per_sec

# IO Status
bool io_in1
bool io_in2
bool io_out1
bool io_out2
bool limit_left
bool limit_right
bool stall_detected

# Motor Status
bool motor_enabled
bool motor_moving
bool motor_calibrated
bool motor_error
uint8 motor_status_code
