controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
    - X_joint
    - Y_joint
    - Z_joint
    - A_joint
    - B_joint
    - C_joint

    command_interfaces:
    - position
    - velocity

    state_interfaces:
    - position
    - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: true
    state_tolerance_check: false  # Disable tolerance checking for simplicity

arctos_hardware_interface:
  ros__parameters:
    motors:
      X_joint:
        motor_id: 1
        requires_homing: true
        inverted: false
        gear_ratio: 13.5
        hardware_type: MKS_57D
        zero_position: 3.0348389535736033
        home_position: -3.028106482337883
        opposite_limit: 2.7484106520134013
        working_current: 2600
        holding_current: 70
        limit_remap_enabled: false
        
      Y_joint:
        motor_id: 2
        requires_homing: true
        inverted: true
        gear_ratio: 150.0
        hardware_type: MKS_57D
        zero_position: 0.8549028328965467
        home_position: -0.8539415382694717
        opposite_limit: 2.0056236341982534
        working_current: 2600
        holding_current: 70
        limit_remap_enabled: false
      
      Z_joint:
        motor_id: 3
        requires_homing: true
        inverted: true
        gear_ratio: 150.0
        hardware_type: MKS_42D
        zero_position: 0.6805250101989999
        home_position: -0.6796301880727333
        opposite_limit: 1.6709090262816064
        working_current: 1800
        holding_current: 70
        limit_remap_enabled: true
      
      A_joint:
        motor_id: 4
        requires_homing: false
        inverted: true
        gear_ratio: 48.0
        hardware_type: MKS_42D
        zero_position: 0.6805250101989999
        home_position: -0.6796301880727333
        opposite_limit: 1.6709090262816064
        working_current: 1400
        holding_current: 70
        limit_remap_enabled: true
      
      B_joint:
        motor_id: 5
        requires_homing: false
        inverted: true
        gear_ratio: 27.3375
        hardware_type: MKS_42D
        zero_position: -0.43627526433400465
        home_position: 0.22467435360166688
        opposite_limit: -0.4228851636789132
        working_current: 1400
        holding_current: 70
        limit_remap_enabled: true
      
      C_joint:
        motor_id: 6
        requires_homing: false
        inverted: true
        gear_ratio: 10
        hardware_type: MKS_42D
        zero_position: -0.3665992422596649
        home_position: -0.0
        opposite_limit: 0.0
        working_current: 1000
        holding_current: 70
        limit_remap_enabled: true
