# ros2_control controller and controller_manager parameters

controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    arctos_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arctos_controller:
  ros__parameters:
    joints:
      - X_joint
      - Y_joint
      - Z_joint
      - A_joint
      - B_joint
      - C_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity

