# This config file is used by ros2_control

arctos_mks_hardware_interface_node:
  ros__parameters:
    motor_can_interface: can0
    motors:
      X_joint:
        motor_id: 1
        hardware_type: "MKS_57D"
        gear_ratio: 13.5
        inverted: false
        working_current: 2600
        holding_current: 70
        requires_homing: true
        limit_remap_enabled: false
      Y_joint:
        motor_id: 2
        hardware_type: "MKS_57D"
        gear_ratio: 150.0
        inverted: true
        working_current: 2600
        holding_current: 70
        requires_homing: true
        limit_remap_enabled: false
      Z_joint:
        motor_id: 3
        hardware_type: "MKS_42D"
        gear_ratio: 150.0
        inverted: false
        working_current: 1800
        holding_current: 70
        requires_homing: true
        limit_remap_enabled: true
      A_joint:
        motor_id: 4
        hardware_type: "MKS_42D"
        gear_ratio: 48.0
        inverted: true
        working_current: 1400
        holding_current: 70
        requires_homing: false
        limit_remap_enabled: true
      B_joint:
        motor_id: 5
        hardware_type: "MKS_42D"
        gear_ratio: 48.0
        inverted: false
        working_current: 1400
        holding_current: 70
        requires_homing: false
        limit_remap_enabled: true
      C_joint:
        motor_id: 6
        hardware_type: "MKS_42D"
        gear_ratio: 1.0
        inverted: false
        working_current: 1400
        holding_current: 70
        requires_homing: false
        limit_remap_enabled: true

controller_manager:
  ros__parameters:
    update_rate: 25  # Hz

    arctos_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arctos_controller:
  ros__parameters:
    joints:
      - X_joint
      - Y_joint
      - Z_joint
      - A_joint
      - B_joint
      - C_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity

