# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  jaw1:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: false
    max_acceleration: 0
  jaw2:
    has_velocity_limits: true
    max_velocity: 100.0
    has_acceleration_limits: false
    max_acceleration: 0
  X_joint:
    has_velocity_limits: true
    max_velocity: 23.271057
    has_acceleration_limits: true
    max_acceleration: 155.140378
  Y_joint:
    has_velocity_limits: true
    max_velocity: 2.094395
    has_acceleration_limits: true
    max_acceleration: 13.962634
  Z_joint:
    has_velocity_limits: true
    max_velocity: 2.094395
    has_acceleration_limits: true
    max_acceleration: 13.962634
  A_joint:
    has_velocity_limits: true
    max_velocity: 6.544985
    has_acceleration_limits: true
    max_acceleration: 43.633231
  B_joint:
    has_velocity_limits: true
    max_velocity: 11.491880
    has_acceleration_limits: true
    max_acceleration: 76.612532
  C_joint:
    has_velocity_limits: true
    max_velocity: 31.415927
    has_acceleration_limits: true
    max_acceleration: 209.439510