# MoveIt uses this configuration for controller management
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arctos_controller

  arctos_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory # Default action namespace for joint_trajectory_controller
    default: true
    joints:
      - X_joint
      - Y_joint
      - Z_joint
      - A_joint
      - B_joint
      - C_joint

