controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arctos_controller:
      type: arctos_controller/ArctosSegmentController

    arctos_servo_controller:
      type: position_controllers/JointGroupPositionController

    gripper_controller:
      type: arctos_controller/ArctosGripperController

arctos_controller:
  ros__parameters:
    joints:
      - X_joint
      - Y_joint
      - Z_joint
      - A_joint
      - B_joint
      - C_joint

arctos_servo_controller:
  ros__parameters:
    joints:
      - X_joint
      - Y_joint
      - Z_joint
      - A_joint
      - B_joint
      - C_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

gripper_controller:
  ros__parameters:
    joint: Left_jaw_joint
    max_opening_m: 0.015
    position_tolerance_m: 0.001
