controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - test_joint
      - joint_y
      
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    # Increased tolerances for testing
    # constraints:
    #   stopped_velocity_tolerance: 0.1    # Increased from 0.01
    #   goal_time: 0.0
    #   test_joint:
    #     trajectory: 0.5                  # Increased from 0.05
    #     goal: 0.3                       # Increased from 0.03
    # limits:
    #   test_joint:
    #     has_position_limits: true
    #     min_position: -3.14159  # -180 degrees in radians
    #     max_position: 3.14159   # +180 degrees in radians
    #     has_velocity_limits: true
    #     max_velocity: 1.0       # Adjust based on your needs
    #     has_acceleration_limits: true
    #     max_acceleration: 1.0   # Adjust based on your needs

    # Allow partial movements
    allow_partial_joints_goal: true      # Added this
    
    # Optionally, can disable state checking during testing
    state_tolerance_check: false         # Added this
arctos_hardware_interface:
  ros__parameters:
    motors:
      test_joint:
        motor_id: 3
        requires_homing: true
        inverted: true
        gear_ratio: 150.0
        hardware_type: MKS_42D
        zero_position: 0.6805250101989999
        home_position: -0.6796301880727333
        opposite_limit: 1.6709090262816064
      joint_y:
        motor_id: 2
        requires_homing: true
        gear_ratio: 150.0
        hardware_type: MKS_57D
        zero_position: 0.8549028328965467
        home_position: -0.8539415382694717
        opposite_limit: 2.0056236341982534
        inverted: true